
name: Continuous Integration with NodeJs

on:
  push: 
    branches: [master]

  pull_request: 
    branches: [master]

env: 
  NODE_ENV: ci
  PORT: 3000

jobs: 
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:        
        mongodb-version: ['4.4']

    steps:    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16      
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.0'

      - run: redis-cli ping
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: client/build      
  
  test:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16 
      - run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: client/build     
      - run: npm start & npx wait-on http://localhost:3000  
      - run: npm test
          

    
