
name: Continuous Integration with NodeJs

on:
  pull_request: 
    branches: [master]

env: 
  NODE_ENV=ci
  PORT=3000

jobs: 
  ci_to_master:
    runs-on: ubuntu-latest

    services:
              mongodb:
                  image: mongo             
                  options: >-
                    --health-cmd mongo
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                  ports:
                    - 27017:27017
              redis: 
                  image: redis
                  ports: 
                    - 6379:6379

    steps:    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run build
