
name: Continuous Integration with NodeJs

on:
  push: 
    branches: [master]

  pull_request: 
    branches: [master]

env: 
  NODE_ENV: ci
  PORT: 3000

jobs: 
  ci_to_master:
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        mongodb-version: ['4.4']

    steps:    
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16      
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.0'

      - run: redis-cli ping
      - run: npm install
      - run: npm run build
      - run: npm test
      
